In [1]:
import sklearn
import music_album_creation as mac
import numpy as np
import matplotlib.pyplot as plt

In [2]:
FC = mac.format_classification.FormatClassifier

In [3]:
music_dir = '/data/music/m/'

In [4]:
model = FC.infer_new('load', music_library_dir=music_dir)

In [9]:
model.x_y_train_set is not None
X, y = model.x_y_train_set

In [16]:
X[:10]

[[301.36],
 [0.0],
 [249.73591666666667],
 [0.0],
 [452.77866666666665],
 [0.0],
 [1238.050525],
 [0.0],
 [268.28],
 [0.0]]

In [23]:
# predict by giving input in seconds
SONG_DURS = [[60], [120], [180], [240], [300], [360], [420], [480]]

# Labels:
# 0 : Timestamp input
# 1 : Duration input
# expect to predict a durations
# expect all ones as predictions since all input are valid song durations
print(model.predict(SONG_DURS))

# expect to predict a durations
# expect all ones as predictions since all input are valid song durations
INPUT = [[1], [2], [3], [4], [5], [6], [7]]
print(model.predict(INPUT))

# expect to predict a timestamp
# expect to get a 0
print(model.predict([[0]]))

# evidence that model is stupid ...
INPUT = [[0], [240], [480], [960], [1200], [1440], [1680]]
print(model.predict(INPUT))


[1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1.]
[0.]
[0. 1. 1. 1. 1. 1. 1.]


In [15]:
print(len(X), type(X), X[0], X[1], X[10])
print(len(y), type(y), y[0], y[1], y[10])
X = np.array(X)
y = np.array(y)

print(len(X), type(X), X.shape, X[0], X[1], X[10])
print(len(y), type(y), y.shape, y[0], y[1], y[10])

from sklearn.datasets import make_blobs

Xn, yn = make_blobs(n_samples=40, centers=2, random_state=0)
print(Xn.shape, yn.shape) = [
    [60], [120], [180], [240], [300], [360], [420]
]

SyntaxError: cannot assign to function call (2324655704.py, line 12)

In [ ]:
print(len(X), type(X), X[0], X[1], X[10])
print(len(y), type(y), y[0], y[1], y[10])
X = np.array(X)
y = np.array(y)

print(len(X), type(X), X.shape, X[0], X[1], X[10])
print(len(y), type(y), y.shape, y[0], y[1], y[10])

from sklearn.datasets import make_blobs

Xn, yn = make_blobs(n_samples=40, centers=2, random_state=0)
print(Xn.shape, yn.shape)

In [7]:
plt.figure(figsize=(10, 5))

<Figure size 1000x500 with 0 Axes>

<Figure size 1000x500 with 0 Axes>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
# from sklearn.datasets import make_blobs
from sklearn.svm import LinearSVC
from sklearn.inspection import DecisionBoundaryDisplay

# X, y = make_blobs(n_samples=40, centers=2, random_state=0)
# X, y = model.x_y_train_set
# X = np.array(X)
plt.figure(figsize=(10, 5))

for i, C in enumerate([1, 100]):
    # "hinge" is the standard SVM loss
    sk_model = model._estimator
    # obtain the support vectors through the decision function
    decision_function = sk_model.decision_function(X)
    # we can also calculate the decision function manually
    # decision_function = np.dot(X, clf.coef_[0]) + clf.intercept_[0]
    # The support vectors are the samples that lie within the margin
    # boundaries, whose size is conventionally constrained to 1
    support_vector_indices = np.where(np.abs(decision_function) <= 1 + 1e-15)[0]
#     print(support_vector_indices)
    support_vectors = X[support_vector_indices]

    plt.subplot(1, 2, i + 1)
#     plt.scatter(X[:, 0], X[:, 1], c=y, s=30, cmap=plt.cm.Paired)
    plt.scatter(X[:, 0], y, c=y, s=30, cmap=plt.cm.Paired)
    ax = plt.gca()
    DecisionBoundaryDisplay.from_estimator(
        sk_model,
        X,
        ax=ax,
        grid_resolution=50,
        plot_method="contour",
        colors="k",
        levels=[-1, 0, 1],
        alpha=0.5,
        linestyles=["--", "-", "--"],
    )
    plt.scatter(
        support_vectors[:, 0],
        support_vectors[:, 1],
        s=100,
        linewidth=1,
        facecolors="none",
        edgecolors="k",
    )
    plt.title("C=" + str(C))
plt.tight_layout()
plt.show()

[(0, 1), (1, 50)]